### ISSUE TITLE
Investigate necessitate of the binary targets in the prisma schema.

### ISSUE THREAD

**Issue by alasdairwilson** [OxfordRSE/gutenberg#301]
```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-3.0.x", "linux-musl-openssl-3.0.x"]
  enums         = true
}
```

This change to binary targets to add musl to the existing debian openssl was added in #300 as an emergency fix to an outage that occurred due to a redeploy while there was an active course that day. The wisdom of this notwithstanding (🤣 ) I can only assume the issue was either caused by the image update in #290  which had never been deployed and so might have broken it or a change in fly.io machine configuration. 

I question whether we should be defining binaryTargets here at all, but it does work for now (and hopefully forever).

**Comment by eatyourgreens** [comment]
I've been seeing errors about Prisma falling back to OpenSSL 1.1.1, but that was EOL in September 2023, and not supported by Node since Node 16.
https://openssl-library.org/post/2023-09-11-eol-111/

**Comment by eatyourgreens** [comment]
I've only done limited testing locally, but upgrading the Prisma client (#316) seems to fix the OpenSSL errors when I build the Docker image on my MacBook.

**Comment by alasdairwilson** [comment]
> I've only done limited testing locally, but upgrading the Prisma client ([#316](https://github.com/OxfordRSE/gutenberg/pull/316)) seems to fix the OpenSSL errors when I build the Docker image on my MacBook.

This was fixed in #314 in commit 2283a0105ce239d8784214c9e29f14be43faa4bf 

which is included in the head of #316 so I suspect that is why it was fixed. 

The real down low on why that was broken by #309 is that the problem it was fixing was inadvertently preventing an issue: the runner was set to node 20.9-alpine which used alpine 3.18 and the builder was set to 20-alpine which uses alpine 3.21. This was changed in that pr.

Prisma downloads ssl-dependent engines when npm/yarn install is run, there is no incompatibility between v4 and v6 as in both can run on any ssl version.

**Comment by eatyourgreens** [comment]
I still get OpenSSL errors locally, even with #314. I'm not sure what the problem is. Architecture maybe? I'm building the Docker image on an M3 MacBook. The errors vanish in #316. It could well be that I'm just doing something wrong when I build the app.

Prisma 6 drops support for Node 16, so that might drop support for OpenSSL 1.1.1.
https://www.prisma.io/docs/orm/more/upgrade-guides/upgrading-versions/upgrading-to-prisma-5#nodejs-minimum-version-change

**Comment by alasdairwilson** [comment]
That is strange! Prisma 6 continues to support openssl 1.0, 1.1 and 3.x. I dunno this issue then. 

There were unique problems on mac builds on friday to be fair both before and after #314, although they were all fixed by this manual openssl update.

Prisma must need to build engines for every combination of ssl (1.0.x, 1.1.x, 3.x) of prisma version and of platform, perhaps there are specific issues for combinations of prisma 4 + openssl + mac architecture but not 6, since the latest release of prisma 4 is prior to m3 then this could be why? It is certainly a deep issue.

This does need fixed then: #316 unfortunately causes a lot of issues out of the box (you already identified we must disable type checking to use it, as eslint even by itself can not run, but also it just hangs for me as it is even with that) both in dev and pre-built.

**Comment by eatyourgreens** [comment]
The only thing I can think of is some difference between `arm64` and `amd64` Docker builds, but I'm just guessing.

**Comment by eatyourgreens** [comment]
>This does need fixed then: https://github.com/OxfordRSE/gutenberg/pull/316 unfortunately causes a lot of issues out of the box (you already identified we must disable type checking to use it, as eslint even by itself can not run, but also it just hangs for me as it is even with that) both in dev and pre-built.

I tried rolling #316 back to Prisma 5.22, but that hangs at the type checking step too. 😞

**Comment by eatyourgreens** [comment]
This Prisma issue suggests manually linking the `libssl` library. The location changed in Alpine 3.21.

```dockerfile
RUN ln -s /usr/lib/libssl.so.3 /lib/libssl.so.3
```

https://github.com/prisma/prisma/issues/25817

**Comment by eatyourgreens** [comment]
Prisma fixed OpenSSL detection in 6.1.0, so that it now searches `/usr/lib` as well as `/lib`. That's probably why I'm not seeing errors on #316.

- https://github.com/prisma/prisma/pull/25824

**Comment by eatyourgreens** [comment]
The fix won't be backported to Prisma 4 or 5, so I think that rules out Node 22 for us until we upgrade Prisma. #298 might need Prisma 6.1.0 or higher.
https://github.com/prisma/prisma/issues/25817#issuecomment-2546431935

**Comment by eatyourgreens** [comment]
I've opened #318 to symlink `libssl` in the `runner` image, but we could also build the runner from `node:20-alpine3.20` to avoid breaking changes in the latest Alpine. I'm not sure which is the best option.

I haven't looked to see if there's a `node:22-alpine3.20` image, for the Next.js 15/React 19 build.
